# fly.toml app configuration file generated for little-glade-1127 on 2023-08-10T17:55:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-glade-1127"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
